### ISSUE TITLE
Ny pull to refresh

### ISSUE THREAD

**Issue by jitendravn** [nylo-core/nylo#129]
##  while using your nypulltorefresh

```DART
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("action")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      NyState.stateUpdated (package:nylo_support/widgets/ny_state.dart:129:13)
#2      NyState.initState.<anonymous closure>.<anonymous closure> (package:nylo_support/widgets/ny_state.dart:94:17)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#4      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#9      _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
#10     _ForwardingStreamSubscription._handleData (dart:as<…>
```

```
NyPullToRefresh(
                                  scrollDirection: Axis.horizontal,
                                  empty:
                                      Center(child: Text('No Articles yet.')),
                                  shrinkWrap: false,
                                  loading: Center(
                                    child: CircularProgressIndicator.adaptive(),
                                  ),
                                  physics: BouncingScrollPhysics(),
                                  onRefresh: () {
                                    _updateFeatureArticles();
                                  },
                                  child: (context, data) {
                                    return featureArticle(data);
                                  },
                                  data: (int iteration) async {
                                    var params = {
                                      'cat_id': catId,
                                      'is_featured': true,
                                      'page': iteration
                                    };
                                    List<Article> data =
                                        await api<ArticleApiService>(
                                      (request) async =>
                                          request.fetchArticles(query: params),
                                    );
                                    return data;
                                  },
                                  stateName: "feature_articles", ),
                                  
```

## I think I have find the error but not solution

the error is in your NY State widget
```
stateUpdated(dynamic data) async {
    if (data['action'] == null) return;

    dynamic stateData = {};
    if (data['data'] != null) {
      stateData = data['data'];
    }
```

**Comment by agordn52** [comment]
Hi @jitendravn, I'll take a look at this 👍

**Comment by agordn52** [comment]
Hi @jitendravn,

I've pushed up a new version of nylo_framework **5.25.6**, can you try that?

**Comment by jitendravn** [comment]
@agordn52 ok sir thanks, i will check this

**Comment by agordn52** [comment]
I'll close this issue but if you continue to have issues let me know.

**Comment by jitendravn** [comment]
@agordn52 nhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null

this is issues is gone

but not able refresh Nypulltorefresh state

**Comment by jitendravn** [comment]
@agordn52 Sir Please look at this

**Comment by agordn52** [comment]
Hi @jitendravn,

You can use `StateAction.refreshPage('YourNyPullToRefreshName');`

Check out the [docs](https://nylo.dev/docs/5.20.0/state-management#state-actions) to learn more.
